apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busy
  name: busy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busy
  template:
    metadata:
      labels:
        app: busy
    spec:
      containers:
      - command:
        - sleep
        - "3000"
        image: busybox
        name: busybox
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: busy
spec:
  scaleTargetRef:
    name: busy     
  minReplicaCount:  1
  maxReplicaCount: 10
  triggers:
  - type: cpu
    metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
    metadata:
      value: "60"
